name: Deploy to IPFS via Pinata

permissions:
  contents: read
  pull-requests: write
  statuses: write

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Upload dist folder to Pinata
        run: |
          BOUNDARY="------------------------$(date +%s)"
          TMP_FILE=$(mktemp)
          
          rm -f $TMP_FILE
          
          # Запись каждого файла в multipart
          find dist -type f | while read filepath; do
            relpath="${filepath#dist/}"
            mimetype=$(file --mime-type -b "$filepath")
          
            echo "Adding: $relpath"
          
            printf -- "--$BOUNDARY\r\n" >> $TMP_FILE
            printf "Content-Disposition: form-data; name=\"file\"; filename=\"$relpath\"\r\n" >> $TMP_FILE
            printf "Content-Type: $mimetype\r\n\r\n" >> $TMP_FILE
            cat "$filepath" >> $TMP_FILE
            printf "\r\n" >> $TMP_FILE
          done
          
          printf -- "--$BOUNDARY--\r\n" >> $TMP_FILE
          
          curl -X POST "https://api.pinata.cloud/pinning/pinFileToIPFS" \
            -H "Authorization: Bearer ${{ secrets.PINATA_JWT }}" \
            -H "Content-Type: multipart/form-data; boundary=$BOUNDARY" \
            --data-binary "@$TMP_FILE"
