name: Deploy to IPFS via Pinata

permissions:
  contents: read
  pull-requests: write
  statuses: write

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Upload dist folder to Pinata
        run: |
          apt-get update && apt-get install -y jq
          
          # Создаём временный multipart файл
          TMP_FILE=$(mktemp)
          BOUNDARY="------------------------$(date +%s)"
          
          echo "--$BOUNDARY" > $TMP_FILE
          
          find dist -type f | while read filepath; do
            relpath="${filepath#dist/}"
            mimetype=$(file --mime-type -b "$filepath")
          
            echo "Adding: $relpath"
          
            cat <<EOF >> $TMP_FILE
          --$BOUNDARY
          Content-Disposition: form-data; name="file"; filename="$relpath"
          Content-Type: $mimetype
    
          EOF
          cat "$filepath" >> $TMP_FILE
          echo "" >> $TMP_FILE
          done
          
          cat <<EOF >> $TMP_FILE
          --$BOUNDARY--
          EOF
          
          curl -X POST "https://api.pinata.cloud/pinning/pinFileToIPFS" \
          -H "Authorization: Bearer ${{ secrets.PINATA_JWT }}" \
          -H "Content-Type: multipart/form-data; boundary=$BOUNDARY" \
          --data-binary "@$TMP_FILE"
          
          rm $TMP_FILE
