name: Deploy to IPFS via Pinata

permissions:
  contents: write
  pull-requests: write
  statuses: write

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Upload to Pinata
        id: upload
        run: echo "cid=$(node .github/pinata-upload.js)" >> "$GITHUB_OUTPUT"
        env:
          PINATA_JWT: ${{ secrets.PINATA_JWT }}

      - name: Show published link
        run: echo "Your DApp is available at https://${{ steps.upload.outputs.cid }}.ipfs.dweb.link"

